yaml_export_config:
  output_file_name: "pipeline_config_output.yaml"
  export_version: "1.0"

config_files:
  promql: "config_templates/promql_config.yaml"
  range: "config_templates/range_config.yaml"
  server: "config_templates/server_config.yaml"
  output: "config_templates/output_config.yaml"

pipelines:
  - id: "pipeline_1"
    name: "Pipeline 1"
    description: "This is the first pipeline."
    promqls:
      - "query_1"
      - "query_range_1"
    ranges:
      - "range_with_datetime"
      - "range_backwards"
    servers:
      - "sandbox_prometheus"
    outputs:
      - "csv_output"
      - "json_output"

  - id: "pipeline_2"
    name: "Pipeline 2"
    description: "This is the second pipeline."
    promqls:
      - "query_2"
      - "query_range_2"
    ranges:
      - "range_with_timestamps"
    servers:
      - "sandbox_prometheus_2"
    outputs: 
      - "pg_store"